#!/usr/bin/env ruby

require "disclose"

unless 2 == ARGV.size
  puts Disclose.usage
  exit 1
end

begin
  instance = Disclose.new *ARGV
  instance.run!
rescue Disclose::Error => e
  STDERR.puts e.message
  exit 1
end
